### ISSUE TITLE
Double license files causes problems with git on Windows

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/xp_redo#37]
Currently there are two license files: `LICENSE.txt` and `license.txt`. The identical (except for case) names are not compatible with the Windows file system, which causes git to merge them (or at least that's what seems to have happened for me), and then say that they have been modified.

I'd suggest either combining the two files, or moving the smaller `license.txt` into the license section of the readme.

**Comment by thomasrudin** [comment]
thanks, haven't noticed that.

Did you by any chance have issues with the `pandorabox-mods` repo lately? 
There are now symlinks in there for the `cool_trees` modpack, i wonder how that works on a windows system...

**Comment by OgelGames** [comment]
> There are now symlinks in there for the `cool_trees` modpack, i wonder how that works on a windows system...

Those didn't work for me, they just appeared as files without extensions, but I  created my own symlinks to them, so wasn't much of a problem. (I actually symlink all of the mods to each world's mod folder anyway)
