### ISSUE TITLE
Disable dig-reward on woodcutting

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/xp_redo#40]
https://github.com/minetest-mods/woodcutting/blob/master/init.lua#L63

```lua
function woodcutting.get_process(playername)
	local process = woodcutting.process_runtime[playername]
	if process then
		process._player = minetest.get_player_by_name(playername)
		if not process._player then
			-- stop process if player leaved the game
			process:stop_process()
			return
		end
	end
	return process
end
```

**Comment by BobFred7** [comment]
Why was this raised as an issue?

**Comment by BuckarooBanzay** [comment]
> Why was this raised as an issue?

Sadly it was heavily abused :confounded:

**Comment by BobFred7** [comment]
> heavily abused
as in just overpowered, or involved in cheating?

**Comment by BuckarooBanzay** [comment]
> as in just overpowered, or involved in cheating?

mostly overpowered: someone just standing around shouldn't get magically rewarded with xp IMO.. :stuck_out_tongue: 

If you have better ideas let me know :+1:

**Comment by BobFred7** [comment]
Maybe I'm wrong, but I think what would be balanced is something between woodcutting fully giving XP and woodcutting giving no XP, which could be achieved by only having a chance to get XP from each node in woodcutting, only getting XP for trunk-type nodes, increased stamina usage, increased durability usage, or a combination of these.

**Comment by BuckarooBanzay** [comment]
> a chance to get XP from each node in woodcutting, only getting XP for trunk-type nodes, increased stamina usage, increased durability usage, or a combination of these.

Hmm, i don't know. XP-Points should be given on manual work, such as digging/placing nodes by hand/axe or crafting stuff in the grid.
