### ISSUE TITLE
display_hover_entity = false and ore ranks => register_rank_entity = nil

### ISSUE THREAD

**Issue by Bastrabun** [mt-mods/xp_redo#42]
ModError: Failed to load and run script from F:\temp\5.2.0\minetest-5.2.0-win64-test\bin\..\mods\xp_redo_ranks_ores\init.lua:
...\minetest-5.2.0-win64-test\bin\..\mods\xp_redo/ranks.lua:6: attempt to call field 'register_rank_entity' (a nil value)
stack traceback:
	...\minetest-5.2.0-win64-test\bin\..\mods\xp_redo/ranks.lua:6: in function 'register_rank'
	....2.0-win64-test\bin\..\mods\xp_redo_ranks_ores/ranks.lua:87: in main chunk
	[C]: in function 'dofile'
	...5.2.0-win64-test\bin\..\mods\xp_redo_ranks_ores\init.lua:4: in main chunk
Siehe debug.txt für Details.

Seems like entity.lua is ruled out by the setting, but when registering ranks from external ranks.lua tries to call xp_redo.register_rank_entity(def) (which is not there) without checking the setting.

**Comment by BuckarooBanzay** [comment]
yeah, that doesn't seem right... :confused:

**Comment by Bastrabun** [comment]
I got around the issue by checking the setting in the ranks.lua before I call register_rank_entity. But that's probably not the way to go :D

xp_redo.ranks = {}

xp_redo.register_rank = function(def)
	table.insert(xp_redo.ranks, def)
	if not xp_redo.disable_hover_entity then
		xp_redo.register_rank_entity(def)
	end
	
end

**Comment by BuckarooBanzay** [comment]
I added a check before registering the actual entity:

https://github.com/mt-mods/xp_redo/blob/bbbd6edca5912b7e5965b8af481836044c3cbfda/ranks.lua#L6-L9
