### ISSUE TITLE
xp.display_hover_entity = true makes entity disappear

### ISSUE THREAD

**Issue by Bastrabun** [mt-mods/xp_redo#43]
Should the settingnames not be the other way round?

currently

xp.display_hover_entity = true

leads to the entity not displayed

xp.display_hover_entity = false

leads to the entity displayed

I'd expect the opposite, when false the entity not shown and when true the entity shown

**Comment by BuckarooBanzay** [comment]
This was a typo, the setting was supposed to be named `xp.disable_hover_entity` (like the variable)
