### ISSUE TITLE
XP bar does not increase on mob punch.

### ISSUE THREAD

**Issue by Git-Forked** [mt-mods/xp_redo#49]
XP does calculate somewhere, as manually adding 1 xp shows a number was there.

**Comment by BuckarooBanzay** [comment]
more info please:
* What setup
* Other mods
* Screenshots
* Steps to reproduce

**Comment by BugReportering** [comment]
### **Minetest server info:** 
```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
```

**Comment by BugReportering** [comment]
![Error_xp_redo_givexp](https://user-images.githubusercontent.com/66106762/110672377-91267f80-819d-11eb-9152-a4e48b96ff16.png)
![Error_xp_redo_xp_bar](https://user-images.githubusercontent.com/66106762/110672401-971c6080-819d-11eb-8879-01699b0f2f5f.png)

**Comment by BugReportering** [comment]
Steps to reproduce: 

1) install mod
2) play the game for awhile or /givexp
3) see xp bar still says 0%
4) play more or /givexp
5) see xp bar still says 0%

**Comment by BugReportering** [comment]
Please reconsider opening this issue. I will provide you additional information if you ask. Thank you.

**Comment by BugReportering** [comment]
This issue may be closed.  xp_redo does not provide ranks, and it must be installed from another separate mod. 

However there are still issues:  Placing nodes does now grant xp, however punching mobs still does not.

**Comment by SwissalpS** [comment]
I just tested and xp-hud updates when punching chickens and kittens. Maybe this was already resolved?

**Comment by BuckarooBanzay** [comment]
> I just tested and xp-hud updates when punching chickens and kittens. Maybe this was already resolved?

:+1: closing this again, feel free to reopen if that problem persists (or open another one)
