### ISSUE TITLE
Undeclared global variable "QoS"

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/xp_redo#53]
`2021-04-25 08:28:32: WARNING[Main]: Undeclared global variable "QoS" accessed at /home/thomas/.minetest/mods/xp_redo/init.lua:30
[MOD] Protector Redo Tool: registered protector:tool for xp_redo:protector
[Mod] xp_redo (081a016/15.03.2021) - (82) end with 15468 KB`

just downloaded version at my start after take it in

**Comment by Festus1965** [comment]
mhh still there ... as I just update failure or issue smashing mods

**Comment by S-S-X** [comment]
This: https://github.com/mt-mods/xp_redo/blob/9da14a2735b06b1a0bc5967903576d61a05f0208/init.lua#L30

Can probably be changed to
```lua
local http = _G.QoS and QoS(minetest.request_http_api(), 2) or minetest.request_http_api()
```
or (if there's something weird going on with _G ...)
```lua
local http = rawget(_G, "QoS") and QoS(minetest.request_http_api(), 2) or minetest.request_http_api()
```
or
```lua
local http = minetest.global_exists("QoS") and QoS(minetest.request_http_api(), 2) or minetest.request_http_api()
```
or
```lua
local http = minetest.get_modpath("qos") and QoS(minetest.request_http_api(), 2) or minetest.request_http_api()
```
and it might silence warning.

Or @Festus1965 another option is to just ignore invalid warning, it is supposed to check if variable is undeclared.

**Comment by OgelGames** [comment]
> * `minetest.global_exists(name)`
Checks if a global variable has been set, without triggering a warning.

So the third option would be the correct one.

**Comment by Festus1965** [comment]
> Or @Festus1965 another option is to just ignore invalid warning, it is supposed to check if variable is undeclared.

I might be able to do this, but I think of the thousand of server admins in the future ... don't let them struggle about the same things over and over
