### ISSUE TITLE
limiter

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/xp_redo#56]
https://github.com/mt-mods/xp_redo/blob/master/builtin.lua#L80

More as of lucky I realized yesterday that there is something changed or wrong in xp-redo

As I calculated the hill size Bonat should dig to get about 100.000 XP it was far less that expected.

As testing then with the legal
* mod multitool ... plus
* mod toll level, toll had level 100 as we most have tools with 1.000.000 digged nodes

I realized that our earlier this year chosen fasted digging option down by flying over the nodes
that from each row digging down and move we get most only 4 of 5 nodes counted, sometimes even only 3 XP out of it.

Whatever the reason for this limiter is (huge Papyrus towers I read) the limiter is set TOO LOW.
WE have proofed in months and thousands of XP that this digging is LEGAL and should not be cut off.

raise the limiter about 20-25%, tell me and I test if it is 'correct; then.

**Comment by Festus1965** [comment]
some real tested counts

3 times with horizontal digging (multi lvl100, fly - 6-7 nodes wide) 1 minute
* 409 - 452 real digged nodes => 336 - 356 got XP (~ 20 % of legal digged nodes lost)

3 times vertical 5 nodes down in a row, flying, same tool 1 minute
* 502-523 real digged nodes => 347 - 363 got XP (~ 30 % of legal digged nodes lost not got XP)

For WAHT there is multitool or even Lava tool and Toolranks, when this builtin mods can not be used in there legal full way ?

To prevent lag as of this high built papyrus tower, the limit in XP is NOT helping against lag, as the lag comes from the massive digged nodes itself, NOT from the gotten XP from it.

**Comment by Festus1965** [comment]
and after a long study from
XP : 5.110.000 to 5.200.000 = + 90.000 XP
digged 109.943 nodes, build 1.518

should be 88.482 XP for digging this 109.943 nodes

a lost of near 20% in digging, or today 20.000 XP missing

**Comment by Festus1965** [comment]
yesterday again:

tool:
diamond multitool, lvl 100

level:
area from +1 up to 65 above water

patterns:
yesterday a lot of sandstone and stone between 0 to 15 level (to enlarge a ocean)

others (above measuring) was:
top with sand (depends on area silver, sand)
under most stone 95% with bulbs of dirt, gravel and coal


used under fly, most vertical, but about 20% also horizontal digging

made 100.000 XP
build count as 7.835
so left XP of digging 92.165 XP out of dig count 109.550 (sandstone, stone)

**Comment by Festus1965** [comment]
a video about real digging there as we do

fig 2.506 proof in 3 counts
XP 1.662

just for a real legal client gamer ... habe fun:

https://youtu.be/bwsCSAR7Ut8

**Comment by Festus1965** [comment]
Whatever you decide:

prepare one easy clear logical answer, that i can give to 
* a random gamer in chat realize this or 
* just to my daughter with 11y to explain it !!!

**Comment by BuckarooBanzay** [comment]
> raise the limiter about 20-25%, tell me and I test if it is 'correct; then.

Increased the setting here by 25%
https://github.com/pandorabox-io/pandorabox.io/commit/93d2c682034446805117e56378bc6a2f41aa65aa
Needs a restart though

Also: please use the proper issue-tracker next time:
* For pandorabox related issues: https://github.com/pandorabox-io/pandorabox.io/issues
* For `xp-redo` related issues (the actual coding stuff, not settings) here

**Comment by S-S-X** [comment]
I did test this a bit and limiters are kind of broken because of timing issues. I've tested a bit alternatives based on moving average, it seems better and reduces effects of inaccurate timing by spreading out checks over larger time frame.
As a small bonus limiter I've tested is bit faster (but will take bit more memory, very small amounts anyway for few numbers...).

**Comment by Festus1965** [comment]
As this is a 'minetest.conf' setting,
there is no restart needed,

just a gamer with server privs an do it on the fly by

/set xp.limit_dig_rate 25

**Comment by S-S-X** [comment]
For the record if anyone happens to be reading this: You cannot change limit_dig_rate runtime using `/set xp.limit_dig_rate 25`. Server needs to be restarted to update configuration.
