### ISSUE TITLE
forget loaded mapblocks after 15 minutes - lost of speed if memory free

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/xp_redo#60]
check your server memory, htop
if there is plenty of NOT used memory (free) after green apps and orange maybe cache

change
https://github.com/pandorabox-io/pandorabox.io/blob/master/minetest.conf#L165

server_unload_unused_data_timeout = 900

to higher value like 3 or even 6 hours (10800 or 21600).
I use 24 hours and so Mapblocks keep longer in FAST memory instead of reloaded if needed. speeds up a lot (at me uses 8 GB RAM mt)
as also a gamer might be out for mining etc. just for 16 minutes and jump /home causes then a reload from HDD

**Comment by S-S-X** [comment]
Does not have anything to do with xp_redo

**Comment by Festus1965** [comment]
mhh, have I been to sleepy ... I clicked issues at mintest.conf ...
ok, I try again at right area ... sorry
