### ISSUE TITLE
can't download through the minetest client

### ISSUE THREAD

**Issue by fluxionary** [mt-mods/xp_redo#65]
it appears to be in the CDB, but searching from in-client (5.6.1, 5.7.0), it doesn't appear for me. 
![image](https://github.com/mt-mods/xp_redo/assets/25628292/b29f5d9d-9cba-4315-95b0-530798dde81b)

**Comment by wsor4035** [comment]
thats because iirc it has the depreciated tag on it

**Comment by BuckarooBanzay** [comment]
> thats because iirc it has the depreciated tag on it

i previously added a note in the cdb:

> I don't intend to develop this mod any further, if you want to adopt/improve it, please let me know

but this was before i moved it to the `mt-mods`, i removed the note and set the mode to `Maintenance Only` will have to transfer it on the cdb to the `mt-mods` org too i guess...
