### ISSUE TITLE
Would like an "announce to all" feature when players rank up.

### ISSUE THREAD

**Issue by Andarius68** [mt-mods/xp_redo#69]
Then everyone on the server can congratulate them and make them feel good about themselves. Might get some conversation going too. :)

**Comment by SwissalpS** [comment]
Take a look at: https://github.com/mt-mods/xp_redo/blob/8324bbe3b4afa75f93e98b22e1b1b17998e96b94/hooks.lua#L4-L16

Your mod can register a hook:
``lua
xp_redo.register_hook({ rank_change = function(playername, sumXP, currentRank)
  minetest.chat_send_all("<spam message>")
end})
``

Hook names: rank_change, xp_change and stat_change
Function signatures vary depending on hook name.

**Comment by BuckarooBanzay** [comment]
(i totally forgot about that label :smile:)

**Comment by Andarius68** [comment]
Ah, okay. Never mind then.
